### ISSUE TITLE
Linux Build Pipeline

### ISSUE THREAD

**Issue by fdiogo** [fdiogo/bityn#12]
Setup the build pipeline for Linux so it can easily be used when a new release is pushed.
Docs: http://electron.atom.io/docs/development/build-instructions-linux/

**Comment by ghost** [comment]
Like, A Jenkins task? or a docker file?

**Comment by fdiogo** [comment]
We use Travis-CI but it shouldn't be too different. Never used Docker so I can't discuss that option. A simple bash script that is ran after testing might just be enough. Preferably something that can run on a Travis env, installing all required dependencies, building, packaging and then pushing the package to a GitHub release. The last part, attaching to a release, I can take care of later.

**Comment by ghost** [comment]
@fdiogo is this done?

**Comment by fdiogo** [comment]
Yes the links provided were to build the actual Electron and not the the project (my bad). It's actually really easy to package. Check package.json
