### ISSUE TITLE
Electron Helper[7104:354023] Couldn't set selectedTextBackgroundColor from default ()

### ISSUE THREAD

**Issue by fdiogo** [fdiogo/bityn#15]
After clicking on track instead of playing the error above is shown. Need more info about this from someone with access to a mac.

**Comment by fdiogo** [comment]
@slayerjain

**Comment by jmeline** [comment]
@fdiogo I am running on a mac and am having a hard time reproducing the error. Clicking on a track doesn't show the error. I am running it with the latest code.

**Comment by fdiogo** [comment]
Yeah the latest code got rid of the package "audio-player" which was supposedly the culprit. Glad to see that bug is gone :) I'll soon start delivering the built packages for all platforms. Thanks @jmeline
